[build]
builder = "NIXPACKS"
buildCommand = "npm install --include=dev && npm --prefix server install --include=dev && npm --prefix server run prisma:generate && npm run build && npm --prefix server run build"

[deploy]
startCommand = "node production.mjs"
healthcheckPath = "/"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
