import { useEffect, useState } from "react";
import { Link, useLocation, useNavigate } from "react-router-dom";
import { speak, stopSpeaking } from "../quiz/speech";
import { learningApplication, type AnswerResult, type SessionView } from "./learningApplication";
import { loadStudentSession } from "../game/utils/studentSession";

export function LearningApp(): JSX.Element {
  const location = useLocation(); const navigate = useNavigate(); const learnerId = loadStudentSession()?.student.id ?? "anonymous";
  const [session, setSession] = useState<SessionView | null>(null); const [answer, setAnswer] = useState(""); const [result, setResult] = useState<AnswerResult | null>(null); const [error, setError] = useState<string | null>(null); const [progress, setProgress] = useState<{ attempts: Array<{ primaryStandardId: string; correct: boolean }>; mastery: Array<{ standardId: string; state: string; nextReviewAt: string | null }>; latestDiagnosticPlacement: { grouping: string; grade: string } | null }>({ attempts: [], mastery: [], latestDiagnosticPlacement: null });
  useEffect(() => () => stopSpeaking(), []);
  useEffect(() => { if (location.pathname === "/learning/practice" || location.pathname === "/learning/diagnostic") void learningApplication.restore().then(setSession); }, [location.pathname]);
  useEffect(() => { if (location.pathname === "/learning/progress") void learningApplication.progress(learnerId).then(setProgress).catch(() => setError("Progress is temporarily unavailable.")); }, [learnerId, location.pathname]);
  const start = async (purpose: "practice" | "diagnostic") => { try { const next = await learningApplication.start(learnerId, purpose); setSession(next); setAnswer(""); setResult(null); setError(null); navigate(`/learning/${purpose}`); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to start learning."); } };
  const submit = async () => { if (!session) return; try { setResult(await learningApplication.submit(session.sessionId, answer)); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to save your answer."); } };
  const advance = async () => { if (!session) return; const next = await learningApplication.next(session.sessionId); if (!next) { navigate("/learning/progress"); return; } setSession(next); setAnswer(""); setResult(null); };
  const choices = session?.question.interaction.choices ?? []; const isQuestion = location.pathname === "/learning/practice" || location.pathname === "/learning/diagnostic";
  return <main className="learning-app"><section className="learning-shell"><header><Link to="/">MOLLY'S LEARNING</Link><nav><Link to="/learning">Learning</Link><Link to="/learning/progress">Progress</Link></nav></header>{location.pathname === "/learning" && <section><p className="eyebrow">COMMON CORE LEARNING</p><h1>What would you like to practise?</h1><div className="actions"><button onClick={() => void start("practice")}>START PRACTICE</button><button className="secondary" onClick={() => void start("diagnostic")}>START DIAGNOSTIC</button></div>{error && <p className="feedback">{error}</p>}</section>}{isQuestion && session && <section className="learning-question"><p className="eyebrow">QUESTION {session.position + 1} OF {session.length}</p>{session.question.interaction.visual && <p className="learning-visual" aria-label={session.question.accessibility.textAlternative}>{"★".repeat(session.question.interaction.visual.count)}</p>}<div className="prompt"><h1>{session.question.prompt.text}</h1><button className="speaker-button" onClick={() => void speak(session.question.accessibility.spokenPrompt ?? session.question.prompt.text)} aria-label="Replay question">🔊</button></div><div className="answer-options">{choices.map((choice) => <button className={answer === choice.label ? "selected" : "secondary"} onClick={() => setAnswer(choice.label)} key={choice.id}>{choice.label}</button>)}</div>{!result ? <button disabled={!answer} onClick={() => void submit()}>CHECK ANSWER</button> : <><p className={result.correct ? "feedback correct" : "feedback"}>{result.explanation}</p><button onClick={() => void advance()}>{result.complete ? "FINISH SESSION" : "CONTINUE"}</button></>}{error && <p className="feedback">{error}</p>}</section>}{location.pathname === "/learning/progress" && <section><p className="eyebrow">LEARNING PROGRESS</p><h1>Your skills</h1><div className="progress-grid">{Object.entries(progress.attempts.reduce<Record<string, { total: number; correct: number }>>((all, attempt) => { const row = all[attempt.primaryStandardId] ?? { total: 0, correct: 0 }; row.total += 1; row.correct += Number(attempt.correct); all[attempt.primaryStandardId] = row; return all; }, {})).map(([standardId, value]) => <article key={standardId}><strong>{standardId}</strong><span>{value.total} attempts · {Math.round(value.correct / value.total * 100)}% correct</span><b>{progress.mastery.find((item) => item.standardId === standardId)?.state ?? "Learning"}</b></article>)}{progress.latestDiagnosticPlacement && <p>Latest check-in: {progress.latestDiagnosticPlacement.grouping} · {progress.latestDiagnosticPlacement.grade}</p>}{!progress.attempts.length && <p>Start a practice session to see your learning activity here.</p>}</div></section>}</section></main>;
}
