import { Injectable } from "@nestjs/common";
import type { Prisma } from "@prisma/client";
import { PrismaService } from "../../prisma/prisma.service";
import type { AttemptEvent, DiagnosticPlacement, LearningSessionRecord, LearningTarget, MasteryRecord, PrerequisiteLink } from "../domain/progress";
import type { ProgressRepository } from "../domain/progress.repository";
import type { SkillEvidenceEvent, SkillProgressRecord } from "../domain/skill-progress";

@Injectable()
export class PrismaProgressRepository implements ProgressRepository {
  constructor(private readonly prisma: PrismaService) {}
  async addAttempt(attempt: AttemptEvent) { try { await this.prisma.curriculumAttemptEvent.create({ data: { ...attempt, supportingStandardIds: attempt.supportingStandardIds, supportingSkillIds: attempt.supportingSkillIds ?? [], supportEvents: attempt.supportEvents ?? [], submittedAnswer: attempt.submittedAnswer as Prisma.InputJsonValue } }); } catch (error) { if ((error as { code?: string }).code !== "P2002") throw error; } }
  async listAttempts(learnerId: string, standardId?: string): Promise<AttemptEvent[]> { return (await this.prisma.curriculumAttemptEvent.findMany({ where: { learnerId, ...(standardId ? { primaryStandardId: standardId } : {}) }, orderBy: { attemptedAt: "asc" } })).map((row) => ({ ...row, supportingStandardIds: row.supportingStandardIds as string[], supportingSkillIds: row.supportingSkillIds as string[], supportEvents: row.supportEvents as string[], submittedAnswer: row.submittedAnswer, purpose: row.purpose as AttemptEvent["purpose"], responseType: row.responseType as AttemptEvent["responseType"] })); }
  async saveMastery(record: MasteryRecord) { await this.prisma.curriculumMasteryRecord.upsert({ where: { learnerId_standardId: { learnerId: record.learnerId, standardId: record.standardId } }, create: record, update: record }); }
  async getMastery(learnerId: string, standardId: string): Promise<MasteryRecord | null> { const row = await this.prisma.curriculumMasteryRecord.findUnique({ where: { learnerId_standardId: { learnerId, standardId } } }); return row ? { ...row, state: row.state as MasteryRecord["state"] } : null; }
  async listMastery(learnerId: string): Promise<MasteryRecord[]> { return (await this.prisma.curriculumMasteryRecord.findMany({ where: { learnerId } })).map((row) => ({ ...row, state: row.state as MasteryRecord["state"] })); }
  async saveLearningTarget(target: LearningTarget) { await this.prisma.curriculumLearningTarget.upsert({ where: { learnerId_standardId: { learnerId: target.learnerId, standardId: target.standardId } }, create: target, update: { active: target.active } }); }
  async listLearningTargets(learnerId: string): Promise<LearningTarget[]> { return this.prisma.curriculumLearningTarget.findMany({ where: { learnerId } }); }
  async listPrerequisites(standardId: string): Promise<PrerequisiteLink[]> { return this.prisma.curriculumPrerequisiteLink.findMany({ where: { standardId } }).then((rows) => rows.map((row) => ({ ...row, source: row.source as PrerequisiteLink["source"] }))); }
  async saveDiagnosticPlacement(placement: DiagnosticPlacement) { await this.prisma.curriculumDiagnosticPlacement.create({ data: { ...placement, learningTargetIds: placement.learningTargetIds, report: placement.report as Prisma.InputJsonValue } }); }
  async listDiagnosticPlacements(learnerId: string): Promise<DiagnosticPlacement[]> { return (await this.prisma.curriculumDiagnosticPlacement.findMany({ where: { learnerId }, orderBy: { completedAt: "desc" } })).map((row) => ({ ...row, learningTargetIds: row.learningTargetIds as string[], report: row.report as Record<string, unknown> })); }
  async saveLearningSession(session: LearningSessionRecord) { await this.prisma.curriculumLearningSession.upsert({ where: { id: session.id }, create: { ...session, state: session.state as Prisma.InputJsonValue }, update: { learnerId: session.learnerId, purpose: session.purpose, seed: session.seed, position: session.position, length: session.length, state: session.state as Prisma.InputJsonValue, status: session.status, completedAt: session.completedAt } }); }
  async findLearningSession(sessionId: string): Promise<LearningSessionRecord | null> { const row = await this.prisma.curriculumLearningSession.findUnique({ where: { id: sessionId } }); return row ? { ...row, purpose: row.purpose as LearningSessionRecord["purpose"], state: row.state as Record<string, unknown>, status: row.status as LearningSessionRecord["status"] } : null; }
  async addSkillEvidence(event: SkillEvidenceEvent): Promise<SkillEvidenceEvent> { try { const row = await this.prisma.curriculumSkillEvidenceEvent.create({ data: { ...event, supportingSkillIds: event.supportingSkillIds, supportEvents: event.supportEvents, response: event.response as Prisma.InputJsonValue } }); return { ...row, supportingSkillIds: row.supportingSkillIds as string[], supportEvents: row.supportEvents as SkillEvidenceEvent["supportEvents"], purpose: row.purpose as SkillEvidenceEvent["purpose"], evidenceMode: row.evidenceMode as SkillEvidenceEvent["evidenceMode"], response: row.response }; } catch (error) { if ((error as { code?: string }).code !== "P2002") throw error; const row = await this.prisma.curriculumSkillEvidenceEvent.findUniqueOrThrow({ where: { learnerId_sessionId_activityInstanceId_purpose: { learnerId: event.learnerId, sessionId: event.sessionId, activityInstanceId: event.activityInstanceId, purpose: event.purpose } } }); return { ...row, supportingSkillIds: row.supportingSkillIds as string[], supportEvents: row.supportEvents as SkillEvidenceEvent["supportEvents"], purpose: row.purpose as SkillEvidenceEvent["purpose"], evidenceMode: row.evidenceMode as SkillEvidenceEvent["evidenceMode"], response: row.response }; } }
  async listSkillEvidence(learnerId: string, skillId?: string): Promise<SkillEvidenceEvent[]> { return (await this.prisma.curriculumSkillEvidenceEvent.findMany({ where: { learnerId, ...(skillId ? { primarySkillId: skillId } : {}) }, orderBy: { attemptedAt: "asc" } })).map((row) => ({ ...row, supportingSkillIds: row.supportingSkillIds as string[], supportEvents: row.supportEvents as SkillEvidenceEvent["supportEvents"], purpose: row.purpose as SkillEvidenceEvent["purpose"], evidenceMode: row.evidenceMode as SkillEvidenceEvent["evidenceMode"], response: row.response })); }
  async saveSkillProgress(record: SkillProgressRecord) { await this.prisma.curriculumSkillProgress.upsert({ where: { learnerId_skillId_skillVersion: { learnerId: record.learnerId, skillId: record.skillId, skillVersion: record.skillVersion } }, create: record, update: record }); }
  async getSkillProgress(learnerId: string, skillId: string, skillVersion: number): Promise<SkillProgressRecord | null> { const row = await this.prisma.curriculumSkillProgress.findUnique({ where: { learnerId_skillId_skillVersion: { learnerId, skillId, skillVersion } } }); return row ? { ...row, state: row.state as SkillProgressRecord["state"], highestCompletedPhase: row.highestCompletedPhase as SkillProgressRecord["highestCompletedPhase"] } : null; }
  async listSkillProgress(learnerId: string): Promise<SkillProgressRecord[]> { return (await this.prisma.curriculumSkillProgress.findMany({ where: { learnerId } })).map((row) => ({ ...row, state: row.state as SkillProgressRecord["state"], highestCompletedPhase: row.highestCompletedPhase as SkillProgressRecord["highestCompletedPhase"] })); }
}
